---
br0:
  type: Bridge
  proto: static
  device: br0
  onboot: yes
  ipv4: 192.168.150.111
  netmask: 255.255.255.0
  gateway: 192.168.150.1
  nm: no

eth0:
  type: Ethernet
  proto: none 
  device: "{{ ansible_default_ipv4.interface }}"
  onboot: yes
  bridge: br0
  nm: no

yum_packages:
  - 'qemu-kvm'
  - 'qemu-img'
  - 'virt-manager'
  - 'libvirt'
  - 'libvirt-python'
  - 'libvirt-client'
  - 'virt-install'
  - 'virt-viewer'
  - 'bridge-utils'
  - '@X Window System'
  - 'xorg-x11-xauth'
  - 'xorg-x11-fonts-*'
  - 'xorg-x11-utils'

vm_workspace: /data/vms/
vm_isos: /data/vms/isos/

iso_wget:
  url: "http://mirrors.mit.edu/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1804.iso"
  name: centos7_minimal.iso
  

vm:
  name: centOS7
  diskpath: "{{ vm_workspace }}centos7.qcow"
  disk_options: ",size=20,bus=virtio,format=qcow2"
  size: 20
  vcpus: 1
  ram: 2048
  iso: "{{ vm_isos }}{{ iso_wget.name }}"
  os: linux

