---
br0:
  type: ETHERNET
  proto: STATIC
  device: br0
  onboot: yes
  ipv4: 192.168.150.185
  netmask: 255.255.255.0
  gateway: 192.168.150.1
  nm: no

eth0:
  type: ETHERNET
  proto: STATIC
  device: "{{ ansible_default_ipv4.interface }}"
  onboot: yes
  bridge: br0
  nm: no

yum_packages:
  - 'qemu-kvm'
  - 'qemu-img'
  - 'virt-manager'
  - 'libvirt'
  - 'libvirt-python'
  - 'libvirt-client'
  - 'virt-install'
  - 'virt-viewer'
  - 'bridge-utils'
  - '"@X Window System"'
  - 'xorg-x11-xauth'
  - '"xorg-x11-fonts-*"'
  - 'xorg-x11-utils'

vm_workspace: /data/vms/
vm_isos: /data/vms/isos/

iso_wget:
  link: http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/current/images/netboot/mini.iso
  name: ubuntu_mini.iso
  

vm:
  name: ubuntu
  diskpath: "{{ vm_workspace }}ubuntu_raw.dsk"
  disk_options: "format=raw,size=40"
  size: 20
  vcpus: 1
  ram: 2048
  iso: "{{ vm_isos }}{{ iso_wget.name }}"
  os: linux

