---
 - name: install MariabDB
   dnf:
     name: "{{ mariadb_packages }}"
     state: latest
   notify:
   - enable/start mariadb

 - name: ensure mariadb service is enabled and started # in case of package already installed
   systemd:
     name: mariadb
     state: started
     enabled: yes

 - name: change selinux to permissive
   copy:
     dest: /etc/selinux/config
     src: selinux.cfg
   notify:
   - disable selinux
 
 - name: install php packages
   dnf:
     name: "{{ php_packages }}"
     state: latest

 - name: drop www.conf template file
   copy:
     src: www.conf
     dest: /etc/php-fpm.d/www.conf
     owner: root
     group: root
     mode: 0644

 - name: make pydio user
   user:
     name: pydio
     comment: pydio service account

 - name: add authorized key to pydio user
   authorized_key:
     user: pydio
     state: present
     key: "{{ pydio_auth_key }}"

# - name: start php-fpm services

 - name: make pydio folder
   file:
     path: "{{ pydio_dir }}"
     owner: pydio
     group: pydio
     mode: 0775
     state: directory

 - name: download pydio cells
   get_url:
     url: "{{ pydio_url }}"
     dest: /opt/pydio/
     mode: 0744

